-- a IMPIEGATI > 29 ANNI
-- SELECT * FROM IMPIEGATI 
-- WHERE Eta > 29
-- FINE

-- b REDDITO ALMENO 800 EURO
-- SELECT * FROM IMPIEGATI 
-- WHERE RedditoMensile >= 800
-- FINE

-- c IMPIEGATI CON DETRAZIONE
-- SELECT * FROM IMPIEGATI
-- WHERE DetrazioneFiscale = 'True' -- o 1 é uguale
-- FINE

-- d IMPIEGATI SENZA DETRAZIONE
-- SELECT * FROM IMPIEGATI
-- WHERE DetrazioneFiscale = 'False'
-- FINE

-- e IMPIEGATI IL CUI COGNOME INIZIA CON LA G E IN ORDINE ALFABETICO
-- SELECT * FROM IMPIEGATI
-- WHERE Cognome LIKE 'G%' ORDER BY Cognome ASC
-- FINE

-- f TOTALE IMPIEGATI
-- SELECT COUNT(*) AS TotImpiegati FROM IMPIEGATI
-- FINE

-- g TOTALE REDDITI MENSILI
-- SELECT SUM(RedditoMensile) AS TotSpesePerRedditiMensili FROM IMPIEGATI
-- FINE

-- h MEDIA REDDITI MENSILI
-- SELECT AVG(RedditoMensile) AS MediaRedditiMensili FROM IMPIEGATI
-- FINE

-- i IMPORTO REDDITO MENSILE MAGGIORE
-- SELECT TOP(1) * FROM IMPIEGATI
-- ORDER BY RedditoMensile DESC
-- FINE

-- j IMPORTO REDDITO MENSILE MINORE
-- SELECT TOP(1) * FROM IMPIEGATI
-- ORDER BY RedditoMensile ASC
-- FINE

-- k IN BASE ALLA DATA
/* SELECT I.*, O.*
FROM IMPIEGATI I
LEFT JOIN IMPIEGOO O ON 
I.IDImpiego = O.IDImpiego  
WHERE YEAR(O.DataAssunzione) BETWEEN 2014 AND 2020
ORDER BY RedditoMensile DESC */

--l FILE PROCEDURE IMPIEGO
-- FINE

-- m ETA MEDIA IMPIEGATI
-- SELECT AVG(Eta) AS EtaMediaImpiegati
-- FROM IMPIEGATI 
-- FINE


-- ####### PROCEDURE #######

-- a FILE PROCEDURE New_IMPIEGATO
-- FINE

-- b FILE PROCEDURE AGGIORNA_IMPIEGATO
-- FINE

-- c FILE PROCEDURE DELETE_IMPIEGATO
--FINE



